### ISSUE TITLE
Email button in navbar

### ISSUE THREAD

**Issue by datawookie** [satRdays/capetown2017#4]
Add an email link/button/icon next to the Twitter icon in the navbar. Would be good to make contact information more visible since there is no Contact entry in the menu.

**Comment by datawookie** [comment]
Ryan do you think you could sort this out when you have a moment?

**Comment by jonmcalder** [comment]
Closed in https://github.com/satRdays/capetown2017/commit/a42ae2040da8a4ac08585bcdbb7cdbd450570cfc 😃
